### ISSUE TITLE
lodash upgrade

### ISSUE THREAD

**Issue by stevetsa** [NCBI-Hackathons/FAIRy-COMPASS#1]
@u8sand - can you upgrade lodash to version 4.17.13 or later?  There has been a security alert.  Thanks.

**Comment by u8sand** [comment]
I guess I was also able to run the assessment again after updating too so we're doing okay with respect to FAIRness so far haha

**Comment by stevetsa** [comment]
Awesome -  Thanks!

**Comment by cishwar** [comment]
awesome!
